/*
 *      Module: Port
 *      File name : Port_PBCfg.h
 *      Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *      Created on: 6 Feb 2024
 *      Author: Abdallah Elgendy
 */

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif



/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
                PORT_A , PORT_P0 , PORTA_P0_DIRECTION , PORTA_P0_RESISTOR , PORTA_P0_MODE , PORTA_P0_LEVEL , PORTA_P0_DIR_CHANGE , PORTA_P0_MODE_CHANGE ,
                PORT_A , PORT_P1 , PORTA_P1_DIRECTION , PORTA_P1_RESISTOR , PORTA_P1_MODE , PORTA_P1_LEVEL , PORTA_P1_DIR_CHANGE , PORTA_P1_MODE_CHANGE ,
                PORT_A , PORT_P2 , PORTA_P2_DIRECTION , PORTA_P2_RESISTOR , PORTA_P2_MODE , PORTA_P2_LEVEL , PORTA_P2_DIR_CHANGE , PORTA_P2_MODE_CHANGE ,
                PORT_A , PORT_P3 , PORTA_P3_DIRECTION , PORTA_P3_RESISTOR , PORTA_P3_MODE , PORTA_P3_LEVEL , PORTA_P3_DIR_CHANGE , PORTA_P3_MODE_CHANGE ,
                PORT_A , PORT_P4 , PORTA_P4_DIRECTION , PORTA_P4_RESISTOR , PORTA_P4_MODE , PORTA_P4_LEVEL , PORTA_P4_DIR_CHANGE , PORTA_P4_MODE_CHANGE ,
                PORT_A , PORT_P5 , PORTA_P5_DIRECTION , PORTA_P5_RESISTOR , PORTA_P5_MODE , PORTA_P5_LEVEL , PORTA_P5_DIR_CHANGE , PORTA_P5_MODE_CHANGE ,
                PORT_A , PORT_P6 , PORTA_P6_DIRECTION , PORTA_P6_RESISTOR , PORTA_P6_MODE , PORTA_P6_LEVEL , PORTA_P6_DIR_CHANGE , PORTA_P6_MODE_CHANGE ,
                PORT_A , PORT_P7 , PORTA_P7_DIRECTION , PORTA_P7_RESISTOR , PORTA_P7_MODE , PORTA_P7_LEVEL , PORTA_P7_DIR_CHANGE , PORTA_P7_MODE_CHANGE ,




                PORT_B , PORT_P0 , PORTB_P0_DIRECTION , PORTB_P0_RESISTOR , PORTB_P0_MODE , PORTB_P0_LEVEL , PORTB_P0_DIR_CHANGE , PORTB_P0_MODE_CHANGE ,
                PORT_B , PORT_P1 , PORTB_P1_DIRECTION , PORTB_P1_RESISTOR , PORTB_P1_MODE , PORTB_P1_LEVEL , PORTB_P1_DIR_CHANGE , PORTB_P1_MODE_CHANGE ,
                PORT_B , PORT_P2 , PORTB_P2_DIRECTION , PORTB_P2_RESISTOR , PORTB_P2_MODE , PORTB_P2_LEVEL , PORTB_P2_DIR_CHANGE , PORTB_P2_MODE_CHANGE ,
                PORT_B , PORT_P3 , PORTB_P3_DIRECTION , PORTB_P3_RESISTOR , PORTB_P3_MODE , PORTB_P3_LEVEL , PORTB_P3_DIR_CHANGE , PORTB_P3_MODE_CHANGE ,
                PORT_B , PORT_P4 , PORTB_P4_DIRECTION , PORTB_P4_RESISTOR , PORTB_P4_MODE , PORTB_P4_LEVEL , PORTB_P4_DIR_CHANGE , PORTB_P4_MODE_CHANGE ,
                PORT_B , PORT_P5 , PORTB_P5_DIRECTION , PORTB_P5_RESISTOR , PORTB_P5_MODE , PORTB_P5_LEVEL , PORTB_P5_DIR_CHANGE , PORTB_P5_MODE_CHANGE ,
                PORT_B , PORT_P6 , PORTB_P6_DIRECTION , PORTB_P6_RESISTOR , PORTB_P6_MODE , PORTB_P6_LEVEL , PORTB_P6_DIR_CHANGE , PORTB_P6_MODE_CHANGE ,
                PORT_B , PORT_P7 , PORTB_P7_DIRECTION , PORTB_P7_RESISTOR , PORTB_P7_MODE , PORTB_P7_LEVEL , PORTB_P7_DIR_CHANGE , PORTB_P7_MODE_CHANGE ,




                PORT_C , PORT_P0 , PORTC_P0_DIRECTION , PORTC_P0_RESISTOR , PORTC_P0_MODE , PORTC_P0_LEVEL , PORTC_P0_DIR_CHANGE , PORTC_P0_MODE_CHANGE ,
                PORT_C , PORT_P1 , PORTC_P1_DIRECTION , PORTC_P1_RESISTOR , PORTC_P1_MODE , PORTC_P1_LEVEL , PORTC_P1_DIR_CHANGE , PORTC_P1_MODE_CHANGE ,
                PORT_C , PORT_P2 , PORTC_P2_DIRECTION , PORTC_P2_RESISTOR , PORTC_P2_MODE , PORTC_P2_LEVEL , PORTC_P2_DIR_CHANGE , PORTC_P2_MODE_CHANGE ,
                PORT_C , PORT_P3 , PORTC_P3_DIRECTION , PORTC_P3_RESISTOR , PORTC_P3_MODE , PORTC_P3_LEVEL , PORTC_P3_DIR_CHANGE , PORTC_P3_MODE_CHANGE ,
                PORT_C , PORT_P4 , PORTC_P4_DIRECTION , PORTC_P4_RESISTOR , PORTC_P4_MODE , PORTC_P4_LEVEL , PORTC_P4_DIR_CHANGE , PORTC_P4_MODE_CHANGE ,
                PORT_C , PORT_P5 , PORTC_P5_DIRECTION , PORTC_P5_RESISTOR , PORTC_P5_MODE , PORTC_P5_LEVEL , PORTC_P5_DIR_CHANGE , PORTC_P5_MODE_CHANGE ,
                PORT_C , PORT_P6 , PORTC_P6_DIRECTION , PORTC_P6_RESISTOR , PORTC_P6_MODE , PORTC_P6_LEVEL , PORTC_P6_DIR_CHANGE , PORTC_P6_MODE_CHANGE ,
                PORT_C , PORT_P7 , PORTC_P7_DIRECTION , PORTC_P7_RESISTOR , PORTC_P7_MODE , PORTC_P7_LEVEL , PORTC_P7_DIR_CHANGE , PORTC_P7_MODE_CHANGE ,



                PORT_D , PORT_P0 , PORTD_P0_DIRECTION , PORTD_P0_RESISTOR , PORTD_P0_MODE , PORTD_P0_LEVEL , PORTD_P0_DIR_CHANGE , PORTD_P0_MODE_CHANGE ,
                PORT_D , PORT_P1 , PORTD_P1_DIRECTION , PORTD_P1_RESISTOR , PORTD_P1_MODE , PORTD_P1_LEVEL , PORTD_P1_DIR_CHANGE , PORTD_P1_MODE_CHANGE ,
                PORT_D , PORT_P2 , PORTD_P2_DIRECTION , PORTD_P2_RESISTOR , PORTD_P2_MODE , PORTD_P2_LEVEL , PORTD_P2_DIR_CHANGE , PORTD_P2_MODE_CHANGE ,
                PORT_D , PORT_P3 , PORTD_P3_DIRECTION , PORTD_P3_RESISTOR , PORTD_P3_MODE , PORTD_P3_LEVEL , PORTD_P3_DIR_CHANGE , PORTD_P3_MODE_CHANGE ,
                PORT_D , PORT_P4 , PORTD_P4_DIRECTION , PORTD_P4_RESISTOR , PORTD_P4_MODE , PORTD_P4_LEVEL , PORTD_P4_DIR_CHANGE , PORTD_P4_MODE_CHANGE ,
                PORT_D , PORT_P5 , PORTD_P5_DIRECTION , PORTD_P5_RESISTOR , PORTD_P5_MODE , PORTD_P5_LEVEL , PORTD_P5_DIR_CHANGE , PORTD_P5_MODE_CHANGE ,
                PORT_D , PORT_P6 , PORTD_P6_DIRECTION , PORTD_P6_RESISTOR , PORTD_P6_MODE , PORTD_P6_LEVEL , PORTD_P6_DIR_CHANGE , PORTD_P6_MODE_CHANGE ,
                PORT_D , PORT_P7 , PORTD_P7_DIRECTION , PORTD_P7_RESISTOR , PORTD_P7_MODE , PORTD_P7_LEVEL , PORTD_P7_DIR_CHANGE , PORTD_P7_MODE_CHANGE ,



                PORT_E , PORT_P0 , PORTE_P0_DIRECTION , PORTE_P0_RESISTOR , PORTE_P0_MODE , PORTE_P0_LEVEL , PORTE_P0_DIR_CHANGE , PORTE_P0_MODE_CHANGE ,
                PORT_E , PORT_P1 , PORTE_P1_DIRECTION , PORTE_P1_RESISTOR , PORTE_P1_MODE , PORTE_P1_LEVEL , PORTE_P1_DIR_CHANGE , PORTE_P1_MODE_CHANGE ,
                PORT_E , PORT_P2 , PORTE_P2_DIRECTION , PORTE_P2_RESISTOR , PORTE_P2_MODE , PORTE_P2_LEVEL , PORTE_P2_DIR_CHANGE , PORTE_P2_MODE_CHANGE ,
                PORT_E , PORT_P3 , PORTE_P3_DIRECTION , PORTE_P3_RESISTOR , PORTE_P3_MODE , PORTE_P3_LEVEL , PORTE_P3_DIR_CHANGE , PORTE_P3_MODE_CHANGE ,
                PORT_E , PORT_P4 , PORTE_P4_DIRECTION , PORTE_P4_RESISTOR , PORTE_P4_MODE , PORTE_P4_LEVEL , PORTE_P4_DIR_CHANGE , PORTE_P4_MODE_CHANGE ,
                PORT_E , PORT_P5 , PORTE_P5_DIRECTION , PORTE_P5_RESISTOR , PORTE_P5_MODE , PORTE_P5_LEVEL , PORTE_P5_DIR_CHANGE , PORTE_P5_MODE_CHANGE ,


                PORT_F , PORT_P0 , PORTF_P0_DIRECTION , PORTF_P0_RESISTOR , PORTF_P0_MODE , PORTF_P0_LEVEL , PORTF_P0_DIR_CHANGE , PORTF_P0_MODE_CHANGE ,
                PORT_F , PORT_P1 , PORTF_P1_DIRECTION , PORTF_P1_RESISTOR , PORTF_P1_MODE , PORTF_P1_LEVEL , PORTF_P1_DIR_CHANGE , PORTF_P1_MODE_CHANGE ,   /* Led pin*/
                PORT_F , PORT_P2 , PORTF_P2_DIRECTION , PORTF_P2_RESISTOR , PORTF_P2_MODE , PORTF_P2_LEVEL , PORTF_P2_DIR_CHANGE , PORTF_P2_MODE_CHANGE ,
                PORT_F , PORT_P3 , PORTF_P3_DIRECTION , PORTF_P3_RESISTOR , PORTF_P3_MODE , PORTF_P3_LEVEL , PORTF_P3_DIR_CHANGE , PORTF_P3_MODE_CHANGE ,
                PORT_F , PORT_P4 , PORTF_P4_DIRECTION , PORTF_P4_RESISTOR , PORTF_P4_MODE , PORTF_P4_LEVEL , PORTF_P4_DIR_CHANGE , PORTF_P4_MODE_CHANGE , /* Switch pin*/



};





